name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    strategy:
      matrix:
        os:
          - { name: Ubuntu 20.04, distro: ubuntu-20.04, gcc_version: 9 }
          - { name: Ubuntu 22.04, distro: ubuntu-22.04, gcc_version: 11 }
        build_type: [Debug, Release]
        toolchain: ["gcc-32bit", "gcc-64bit"]

    name: "${{matrix.os.name}} ${{matrix.build_type}} ${{matrix.toolchain}}"
    runs-on: ${{matrix.os.distro}}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash
        run: sudo apt-get install gcc g++ gcc-multilib libstdc++-${{matrix.os.gcc_version}}-dev lib32stdc++-${{matrix.os.gcc_version}}-dev

      - name: Create build environment
        working-directory: ${{runner.workspace}}
        run: mkdir build

      - name: Initialize CMake
        shell: bash
        env:
          CC: /usr/bin/gcc
          CXX: /usr/bin/g++
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_TOOLCHAIN_FILE=toolchains/${{matrix.toolchain}}.cmake

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: make

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -V -C ${{matrix.build_type}}

      - name: Rename library artifact
        run: mv ${{runner.workspace}}/build/src/libgluasteal.so ${{runner.workspace}}/build/gluasteal-${{matrix.os.distro}}-gcc${{matrix.os.gcc_version}}-${{matrix.toolchain}}-${{matrix.build_type}}.so

      - uses: actions/upload-artifact@v4
        with:
          name: gluasteal-${{matrix.os.distro}}-gcc${{matrix.os.gcc_version}}-${{matrix.toolchain}}-${{matrix.build_type}}
          path: ${{runner.workspace}}/build/gluasteal-${{matrix.os.distro}}-gcc${{matrix.os.gcc_version}}-${{matrix.toolchain}}-${{matrix.build_type}}.so
          if-no-files-found: error
          retention-days: 14
